project_id = "ioqogdxfmapcijmqjcpb"

[functions.get-onesignal-config]
verify_jwt = true

[functions.track-referral-click]
verify_jwt = false

[functions.places-photo]
verify_jwt = false

[functions.process-visit-reminders]
verify_jwt = false

[functions.check-paused-recommenders]
verify_jwt = false

[functions.user-location]
verify_jwt = true

[functions.register-device-token]
verify_jwt = true

[functions.send-nearby-notification]
verify_jwt = true

[functions.get-maps-config]
verify_jwt = true

[functions.test-email]
verify_jwt = false

[functions.send-recommendation-email]
verify_jwt = true
