project_id = "edazolwepxbdeniluamf"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://edazolwepxbdeniluamf.supabase.co"]
jwt_expiry = 3600
enable_signup = true
enable_anonymous_sign_ins = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[db]
enabled = true
port = 54322
shadow_port = 54325
major_version = 15

[functions]
enabled = true
port = 54321

[functions.send-notification]
verify_jwt = false

[functions.award-points]
verify_jwt = false

[functions.auto-close-requests]
verify_jwt = false

[realtime]
enabled = true
port = 54323
ip_version = "ipv6"

[storage]
enabled = true
port = 54324
file_size_limit = "50MiB"
image_transformation = { enabled = true }

[edge-runtime]
enabled = true
port = 54322
ip_version = "ipv4"

[analytics]
enabled = false
port = 54327
vector_port = 54328
backend = "postgres"